# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\sql_server\output\SQL_server_app\edit_data_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(406, 388)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(100, 270, 191, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton:hover {\n"
"    background-color: #ffdbcc;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #fcb9aa;\n"
"}\n"
"QPushButton {\n"
"    background-color: rgb(57, 208, 208);\n"
"    border-radius: 31px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.name_input = QtWidgets.QLineEdit(self.centralwidget)
        self.name_input.setGeometry(QtCore.QRect(50, 20, 301, 51))
        self.name_input.setObjectName("name_input")
        self.last_name_input = QtWidgets.QLineEdit(self.centralwidget)
        self.last_name_input.setGeometry(QtCore.QRect(50, 80, 301, 51))
        self.last_name_input.setObjectName("last_name_input")
        self.password_input = QtWidgets.QLineEdit(self.centralwidget)
        self.password_input.setGeometry(QtCore.QRect(50, 140, 301, 51))
        self.password_input.setObjectName("password_input")
        self.role_input = QtWidgets.QLineEdit(self.centralwidget)
        self.role_input.setGeometry(QtCore.QRect(50, 200, 301, 51))
        self.role_input.setObjectName("role_input")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Изменить"))
        self.name_input.setPlaceholderText(_translate("MainWindow", "Введите новое имя"))
        self.last_name_input.setPlaceholderText(_translate("MainWindow", "Введите новую фамилию"))
        self.password_input.setPlaceholderText(_translate("MainWindow", "Введите новый пароль"))
        self.role_input.setPlaceholderText(_translate("MainWindow", "Введите новый роль"))
